### ISSUE TITLE
Any idea how to get this working with Roots WordPress?

### ISSUE THREAD

**Issue by stuartcusackie** [aginev/wp-glide#3]
Hi. I'm trying to get this working with the [Roots framework](https://roots.io/) for WordPress.

The wp_glide_image function seems to be firing correctly but I don't see any images being generated, and the urls look a bit funny:

This:
`http://mywebsite.test/app/themes/mytheme/public/images/heros/hero1.jpg`

Becomes this:
`http://mywebsite.test/wp/img/w128/mywebsite.test/app/themes/mytheme/public/images/heros/hero1.jpg`

It may not be compatible with the Roots Bedrock configuration but I just thought I'd ask.

Thanks for the package!

**Comment by aginev** [comment]
This package was tried a long time ago at a single site and never used again. In general it adds much flexible image manipulations at WP, but not thinking that force using non WP specific image methods is a good idea, because no other hooks will be executed on it.

**Comment by stuartcusackie** [comment]
Gotcha. No problem at all, just thought i'd ask.

Thanks!
